# Generated by Django 2.0.2 on 2019-07-30 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='about_me',
            field=models.TextField(blank=True, help_text='Максимум 160 сиимволов.', max_length=160),
        ),
    ]
