# Generated by Django 2.0.2 on 2019-07-10 16:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180, unique=True, verbose_name='Введите заголовок')),
                ('slug', models.SlugField(max_length=220, verbose_name='slug')),
                ('image', models.ImageField(blank=True, default='no_image_app_content.jpg', null=True, upload_to='users/%Y/%d', verbose_name='Загрузить изображение')),
                ('entry', models.TextField(blank=True, verbose_name='Запись')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_created', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
