# Generated by Django 2.0.2 on 2019-07-11 14:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social_content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='users_like',
            field=models.ManyToManyField(blank=True, related_name='contents_liked', to=settings.AUTH_USER_MODEL),
        ),
    ]
